### ISSUE TITLE
Beware - current version of org.reflections dependency is not thread safe

### ISSUE THREAD

**Issue by mcrmfc** [racc/typesafeconfig-guice#7]
https://github.com/ronmamo/reflections/issues/81

Reproduced very simply via this library.

It looks like the only current workaround is to downgrade to 0.9.9.

I will try that and report back.

**Comment by mcrmfc** [comment]
@racc - when you get a chance would it be possible to do a release to make this fix available

**Comment by racc** [comment]
@mcrmfc Ok it's released under 0.0.4 now. Enjoy!
